name: Deploy Booklet

on:
  push:
    branches: [main]
    # paths: [docs/**]
  pull_request:
    branches: [main]
    # paths: [docs/**]

jobs:
  deploy:
    - uses: applics/booklet-actions/.gihub/workflows/deploy.yaml@main
      with:
        booklet_token: ${{ secrets.booklet_token }}
        booklet_cname: ${{ secrets.booklet_cname }}
