name: Deploy Booklet

on:
  push:
    branches: [main]
    paths: [docs/**]
  pull_request:
    branches: [main]
    paths: [docs/**]

jobs:
  deploy:
    uses: applicdev/booklet/.github/workflows/deploy.yaml@main
    secrets:
      booklet_token: ${{ secrets.booklet_token }}
      booklet_cname: ${{ secrets.booklet_cname }}
